### ISSUE TITLE
"El tiempo ya"

### ISSUE THREAD

**Issue by juanmi-gh** [Kotlin-Boom-gang/TDD-Kotlin-Team#2]
API para recibir la previsión meteorológica en formato frase coloquial ("Hace mucho calor", "Va a llover", "Alerta por viento y nieve", "Se pueden freír huevos en la calzada"...).

La idea es recopilar la información meteorólógica de algún API público y ofrecer la respuesta adecuada a la información recibida.
- Implica comunicación con API público.
- Recoger información de localización del usuario.
- Analizar la información recibida y ofrecer respuesta en un plazo muy breve.

Posibles iteraciones:
- Recoger del usuario el momento para el que solicita la información (por defecto ahora mismo, ser podrían ofrecer intervalos futuros de más rango)
- Sistema de alertas y alarmas definidas por el usuario.
- Ofrecer resultados en formato audio

**Comment by roe963** [comment]
:ok_hand:

**Comment by juanmi-gh** [comment]
Tiramos por aquí entonces ✔️
