### ISSUE TITLE
Permisos admin en organización

### ISSUE THREAD

**Issue by juanmi-gh** [Kotlin-Boom-gang/TDD-Kotlin-Team#5]
Buenas @RMarinoS, quería probar a enganchar un bot de telegram al repo para que nos avise cuando haya una pull-request nueva y cosas así para no tener que estar pendiente del email. 

¿Nos puedes poner con acceso admin en la organización? Creo que al estar el repo relacionado con la organización no me deja conectar con el bot.
Gracias.

![Screenshot 2021-06-07 at 08 16 55](https://user-images.githubusercontent.com/4533397/120968115-be68d680-c768-11eb-8bf7-4d81d79c23a3.png)

**Comment by RMarinoS** [comment]
Hola Juanmi,

Os he añadido a los presentes roles de "Owner" en la organización
